# -*- coding: utf-8 -*-
"""
Author: Daniel Heink
"""
import numpy as np
import matplotlib.pyplot as plt


def gcode_to_array(path):
    """
    Takes gcode and returns the individual continuous paths subdivided into moves that are defined through [X,Y,Z, Feedrate, Extruder]


    Parameters
    ----------
    path : string
        Path of the file that is to be converted

    Returns
    -------
    printpaths_sorted : list
        List of the individual continuous paths subdivided into moves

    """

    gcode = open(path)
    
    #remove comments 
    gcode = [line for line in gcode if not line.startswith(";")]
    
    #remove lines with non G1 or G0 command
    gcode = [line for line in gcode if line.startswith('G1') or line.startswith('G0')]
    
    #group by moves 
    printpaths = []
    temp = []
    for line in gcode: 
        if line.startswith('G0'):
            if temp:
                printpaths.append(temp)
                temp = []
                temp.append(line)
            else:
                temp.append(line)
                
        elif line.startswith('G1'):
            temp.append(line)
            
        else:
            if temp:
                printpaths.append(temp)
                temp = []
                printpaths.append(line)
            else: 
                printpaths.append(line)
    
    #seperate into Parameters 
    current_params = [0 for i in range(5)]
    printpaths_sorted = []          #final list containing all paths with its moves and parameters 
    for printpath in printpaths: 
        printpath_sorted = []       #contains the single path that is to be analyzed and added
        for line in printpath:
            params = line.split()
            x = y = z = e = f = None
            for param in params:
                
                if param.startswith('X'):
                    try:
                        current_params[0] = x = float(param[1:])
                    except:
                        x = current_params[0]
                else:
                    x = current_params[0]
                    
                if param.startswith('Y'):
                    try:
                        current_params[1] =y = float(param[1:])
                    except:
                        y = current_params[1]
                else:
                    y = current_params[1]
                    
                if param.startswith('Z'):
                    try:
                        current_params[2] = z = float(param[1:])
                    except:
                        z = current_params[2]
                else:
                    z = current_params[2]
                    
                if param.startswith('F'):
                    try:
                        current_params[4] = f = float(param[1:])
                    except:
                        f = current_params[4]
                else:
                    f = current_params[4]
                    
                    
                if param.startswith('E'):
                    try:
                        current_params[3] = e = float(param[1:])
                    except:
                        e = current_params[3]
                else:
                    e = current_params[3]
                    
            printpath_sorted.append([x,y,z,e,f])
        printpaths_sorted.append(np.array(printpath_sorted))
    return printpaths_sorted


def visualize_paths(pathlist, include_positioning_move=False): 
    '''
    This function visualizes a given list of paths in 3 dimensional space. Every path needs to consist of moves which start with X,Y,Z    

    Parameters
    ----------
    pathlist : list
        List of all the paths as numpy arrays like generated by gcode_to_array.
    include_positioning_move : boolean, optional
        Turns the display of G0 moves on or off. The default is False.

    Returns
    -------
    None.

    '''
    plt.figure().add_subplot(projection = '3d')
    for path in pathlist:
        if not include_positioning_move:
            if path.shape[0]>2:
                path = np.delete(path, (0), axis=0)
        
        
        plt.plot(path[:,0],path[:,1], path[:,2])
    plt.axis('scaled')

